#!/bin/env python
import optparse
import loadcanamespace
import os.path

def main():
    p = optparse.OptionParser(usage="%prog -c CERTDIR -m MESSAGE", version = "%prog 0.1 ")
    p.add_option('-m', '--message', action ='append', 
        help='adds a message to be tested.', metavar='MESSAGE')
    p.add_option('-c', '--certs-dir', action ='store', 
        help='Path of certificates dir',
        default='/etc/grid-security/certificates/', metavar='CERTDIR')
    options, arguments = p.parse_args()
    anchor =  loadcanamespace.ViewTrustAnchor()
    anchor.update_ca_list(options.certs_dir)
    for item in options.message:
        if os.path.isfile(item):
            if anchor.validate_file(item):
                print "Message: " + item + " is valid"
            else:
                print "Signature of message " + item + " could not be verified."
        else:
            print "File " + item + " does not exist."
       
if __name__ == "__main__":
    main()
